blank_issues_enabled: false
contact_links:
  - name: Transaction Form 1
    url: https://treasuryguild.github.io/NFT-Guild/
    about: Fill in this form when you make a transaction (Complete form 1 and 2)
  - name: Tasks/Misc/Expenses
    url: https://docs.google.com/forms/d/e/1FAIpQLScuevizHMI0kXgj3VOP1Ch5PawHgZ8SpvfUjpLhXTBWClqJhQ/viewform?usp=sf_link
    about: Google form for tasks/misc/expense ADA requests to be completed by Co-/Proposer
