name: Transaction Form 2
description: Fill in this form when you make a transaction (Complete form 1 and 2)
title: "NFT Guild Transaction Issue Form"
labels: ["Transactions"]
assignees:
  - miroslavrajh
body:
  - type: markdown
    attributes:
      value: |
        Please fill in the details of the transaction
  - type: dropdown
    id: pool
    attributes:
      label: Pool
      description: Please select the funded proposal that will pay for this
      options:
        - NFT Guild
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Name
      description: Please enter the name of beneficiary.
      placeholder: ex. Kenric Nelson
    validations:
      required: true
  - type: input
    id: amount
    attributes:
      label: Amount of ADA
      description: Please enter the amount of ADA.
      placeholder: ex. 200 ADA or $ amount
    validations:
      required: true
  - type: input
    id: txhash
    attributes:
      label: Transaction ID
      description: Please enter the transaction ID.
      placeholder: ex. 427b473ca6c643578121745dc2f39f6e7e1681e25bf334d87305aaae73c2216f
    validations:
      required: true
  - type: dropdown
    id: budgetb
    attributes:
      label: Budget Item
      description: Please select the budget item.
      options:
        - Incoming IOG
        - Biweekly events
        - Marketing & Outreach Campaign
        - Building Website
        - Management & Coordination
    validations:
      required: true
  - type: textarea
    id: Comment
    attributes:
      label: Description/Extra Comments
      description: Description/Extra comments about transaction.
      placeholder: ex. This is a monthly fee, please pay this on the 3rd of each month?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Agree the information is correct
      description: By submitting this issue, you agree the information provided is correct.
      options:
        - label: I agree the information provided is correct.
          required: true
